annotations:
  artifacthub.io/alternativeName: paperless
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/paperless-ngx/paperless-ngx Docker tag to v1.14.5
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/paperless-ngx/paperless-ngx
    - name: Chart Source
      url: https://github.com/gabe565/charts/tree/main/charts/paperless-ngx
apiVersion: v2
appVersion: 1.14.5
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.0
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.7
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.5.6
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 17.9.3
description: 'A community-supported supercharged version of paperless: scan, index
  and archive all your physical documents'
home: https://charts.gabe565.com/charts/paperless-ngx/
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/b948750d558b58018d1d3393db145d162d44fceb/src-ui/src/assets/logo-notext.svg
keywords:
- documents
- ocr
- paper
kubeVersion: '>=1.22.0-0'
name: paperless-ngx
sources:
- https://github.com/paperless-ngx/paperless-ngx
type: application
version: 0.4.1
